-- Restaurants
INSERT INTO RESTAURANTS (PEANUT_ALLERGY_RATING, EGG_ALLERGY_RATING, DAIRY_ALLERGY_RATING, TOTAL_RATING, ZIP_CODE, RESTAURANT_NAME) VALUES (5.0, 4.0, 3.0, 4.0, '55140', 'Wingstop');
INSERT INTO RESTAURANTS (PEANUT_ALLERGY_RATING, EGG_ALLERGY_RATING, DAIRY_ALLERGY_RATING, TOTAL_RATING, ZIP_CODE, RESTAURANT_NAME) VALUES (5.0, 4.0, 4.0, 4.3, '55140', 'Chipotle');
INSERT INTO RESTAURANTS (PEANUT_ALLERGY_RATING, EGG_ALLERGY_RATING, DAIRY_ALLERGY_RATING, TOTAL_RATING, ZIP_CODE, RESTAURANT_NAME) VALUES (5.0, 3.0, 4.3, 4.1, '55721', 'Chick-fil-a');

-- Users                  wanted to be 'STATE' but reserved keyword
INSERT INTO USERS (USER_NAME, CITY, STATES, ZIP_CODE, INTEREST_IN_PEANUT_ALLERGIES, INTEREST_IN_EGG_ALLERGIES, INTEREST_IN_DAIRY_ALLERGIES, IS_MODERATOR) VALUES ('BonelessHam', 'Chiyoda Ku', 'Tokyo', '100-0004', false, false, true, true);
INSERT INTO USERS (USER_NAME, CITY, STATES, ZIP_CODE, INTEREST_IN_PEANUT_ALLERGIES, INTEREST_IN_EGG_ALLERGIES, INTEREST_IN_DAIRY_ALLERGIES, IS_MODERATOR) VALUES ('TommyTuffKnuckles', 'Fresno', 'California', '55140', true, true, true, false);
INSERT INTO USERS (USER_NAME, CITY, STATES, ZIP_CODE, INTEREST_IN_PEANUT_ALLERGIES, INTEREST_IN_EGG_ALLERGIES, INTEREST_IN_DAIRY_ALLERGIES, IS_MODERATOR) VALUES ('Green Pump', 'San Bernardino', 'California', '55330', false, false, true, false);
INSERT INTO USERS (USER_NAME, CITY, STATES, ZIP_CODE, INTEREST_IN_PEANUT_ALLERGIES, INTEREST_IN_EGG_ALLERGIES, INTEREST_IN_DAIRY_ALLERGIES, IS_MODERATOR) VALUES ('Samuel Jack', 'San Bernardino', 'California', '55330', false, true, true, false);

-- Reviews
INSERT INTO DINING_REVIEWS (REVIEW_NAME, PEANUT_SCORE, EGG_SCORE, DAIRY_SCORE, COMMENTARY, REVIEW_STATUS, RESTAURANT_ID ) VALUES ('Perfect!', 5.0, 4.0, 3.0, 'Best wings in town!', 'APPROVED', 1);
INSERT INTO DINING_REVIEWS (REVIEW_NAME, PEANUT_SCORE, EGG_SCORE, DAIRY_SCORE, COMMENTARY, REVIEW_STATUS, RESTAURANT_ID ) VALUES ('Nice', 5.0, 4.0, 4.0, 'Some tasty fresh healthy food', 'APPROVED', 2);
INSERT INTO DINING_REVIEWS (REVIEW_NAME, PEANUT_SCORE, EGG_SCORE, DAIRY_SCORE, COMMENTARY, REVIEW_STATUS, RESTAURANT_ID ) VALUES ('Scam', 3.0, 1.0, 2.0, 'Bullsh*t portion sizes, expensive', 'PENDING', 2);
INSERT INTO DINING_REVIEWS (REVIEW_NAME, PEANUT_SCORE, EGG_SCORE, DAIRY_SCORE, COMMENTARY, REVIEW_STATUS, RESTAURANT_ID ) VALUES ('Tasty', 5.0, 4.0, 4.3, 'Great customer service, great food!', 'APPROVED', 3);
